#!/usr/bin/env python3
"""从板级传感器 manifest 按 PX4 固定 Device::DeviceId 位布局生成设备 ID。"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys


class ContractError(RuntimeError):
    """The authoritative board sensor manifest is invalid."""


BUS_TYPES = {
    "UNKNOWN": 0,
    "I2C": 1,
    "SPI": 2,
    "UAVCAN": 3,
    "SIMULATION": 4,
    "SERIAL": 5,
    "MAVLINK": 6,
}
SYMBOL_PATTERN = re.compile(r"^[A-Z][A-Za-z0-9]*$")
GIT_COMMIT_PATTERN = re.compile(r"^[0-9a-fA-F]{40}(?:[0-9a-fA-F]{24})?$")


def load_manifest(path: pathlib.Path) -> dict:
    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ContractError(f"unable to load sensor device manifest: {error}") from error
    if not isinstance(manifest, dict) or manifest.get("schema_version") != 1:
        raise ContractError("sensor device schema_version must be 1")
    reference = manifest.get("px4_reference")
    if not isinstance(reference, dict):
        raise ContractError("px4_reference must be an object")
    commit = reference.get("commit")
    if not isinstance(commit, str) or not GIT_COMMIT_PATTERN.fullmatch(commit):
        raise ContractError("px4_reference.commit must be a full Git object ID")
    return manifest


def require_uint(value: object, field: str, maximum: int) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise ContractError(f"{field} must be an integer")
    if value < 0 or value > maximum:
        raise ContractError(f"{field} must be in range 0..{maximum}")
    return value


def parse_device_type(value: object, field: str) -> int:
    if not isinstance(value, str) or not re.fullmatch(r"0x[0-9a-fA-F]{2}", value):
        raise ContractError(f"{field} must be a two-digit hexadecimal string")
    return int(value, 16)


def load_devices(manifest: dict) -> list[dict]:
    """校验设备字段并生成唯一非零 ID；符号、总线和地址清单只来自 manifest。"""
    source = manifest.get("devices")
    if not isinstance(source, list) or not source:
        raise ContractError("devices must be a non-empty array")
    devices: list[dict] = []
    symbols: set[str] = set()
    ids: set[int] = set()
    for index, entry in enumerate(source):
        field = f"devices[{index}]"
        if not isinstance(entry, dict):
            raise ContractError(f"{field} must be an object")
        symbol = entry.get("symbol")
        name = entry.get("name")
        bus_type_name = entry.get("bus_type")
        if not isinstance(symbol, str) or not SYMBOL_PATTERN.fullmatch(symbol):
            raise ContractError(f"{field}.symbol must be a C++ identifier suffix")
        if symbol in symbols:
            raise ContractError(f"duplicate sensor symbol {symbol}")
        if not isinstance(name, str) or not name.strip():
            raise ContractError(f"{field}.name must be a non-empty string")
        if bus_type_name not in BUS_TYPES:
            raise ContractError(f"{field}.bus_type is not a PX4 bus type")
        bus_type = BUS_TYPES[bus_type_name]
        bus = require_uint(entry.get("bus"), f"{field}.bus", 31)
        address = require_uint(entry.get("address"), f"{field}.address", 255)
        device_type = parse_device_type(entry.get("device_type"), f"{field}.device_type")
        # PX4 DeviceId = bus_type[2:0] | bus[7:3] | address[15:8] |
        # device_type[23:16]；高 8 位固定为 0。
        device_id = bus_type | (bus << 3) | (address << 8) | (device_type << 16)
        if device_id == 0 or device_id in ids:
            raise ContractError(f"duplicate or zero PX4 device ID 0x{device_id:08x}")
        symbols.add(symbol)
        ids.add(device_id)
        devices.append(
            {
                "symbol": symbol,
                "name": name.strip(),
                "bus_type_name": bus_type_name,
                "bus_type": bus_type,
                "bus": bus,
                "address": address,
                "device_type": device_type,
                "device_id": device_id,
            }
        )
    return devices


def render_header(manifest: dict, devices: list[dict]) -> bytes:
    lines = [
        "// Generated by tools/sensors/generate_device_contract.py. Do not edit.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace dima::generated::sensor_devices {",
        "",
    ]
    for device in devices:
        symbol = device["symbol"]
        lines.extend(
            [
                f"// {device['name']}: {device['bus_type_name']} bus {device['bus']}, "
                f"address {device['address']}, PX4 devtype 0x{device['device_type']:02x}.",
                f"inline constexpr std::uint32_t k{symbol}DeviceId = "
                f"0x{device['device_id']:08x}U;",
            ]
        )
    lines.extend(
        [
            "",
            "} // namespace dima::generated::sensor_devices",
            "",
        ]
    )
    return "\n".join(lines).encode("utf-8")


def render_catalog(manifest: dict, devices: list[dict]) -> bytes:
    catalog = {
        "schema_version": 1,
        "px4_reference": manifest["px4_reference"],
        "devices": devices,
    }
    return (json.dumps(catalog, indent=2, sort_keys=True) + "\n").encode("utf-8")


def write_if_changed(path: pathlib.Path, content: bytes) -> None:
    if path.is_file() and path.read_bytes() == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_bytes(content)
    temporary.replace(path)


def generate(manifest: dict, output: pathlib.Path, verify: bool) -> None:
    """同时生成 C++ 常量与 JSON catalogue，verify 时逐字节拒绝陈旧派生物。"""
    devices = load_devices(manifest)
    files = {
        output / "SensorDeviceContract.hpp": render_header(manifest, devices),
        output / "sensor_devices.json": render_catalog(manifest, devices),
    }
    if verify:
        mismatches = [
            str(path)
            for path, expected in files.items()
            if not path.is_file() or path.read_bytes() != expected
        ]
        if mismatches:
            raise ContractError(
                "generated sensor device contract is stale: " + ", ".join(mismatches)
            )
        print(f"verified {len(devices)} generated sensor device IDs in {output}")
        return
    for path, content in files.items():
        write_if_changed(path, content)
    values = ", ".join(
        f"{device['name']}=0x{device['device_id']:08x}" for device in devices
    )
    print(f"generated {len(devices)} PX4 sensor device IDs: {values}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    parser.add_argument("--verify", action="store_true")
    arguments = parser.parse_args()
    generate(load_manifest(arguments.manifest), arguments.output, arguments.verify)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ContractError as error:
        print(f"sensor device generation failed: {error}", file=sys.stderr)
        raise SystemExit(1)
