#ifndef H743_SYSFLASH_H
#define H743_SYSFLASH_H

#define FLASH_AREA_BOOTLOADER           0
#define FLASH_AREA_IMAGE_PRIMARY_ID     1
#define FLASH_AREA_IMAGE_SECONDARY_ID   2
#define FLASH_AREA_IMAGE_SCRATCH        3

#define FLASH_AREA_IMAGE_PRIMARY(x)     FLASH_AREA_IMAGE_PRIMARY_ID
#define FLASH_AREA_IMAGE_SECONDARY(x)   FLASH_AREA_IMAGE_SECONDARY_ID

#endif /* H743_SYSFLASH_H */
