#!/usr/bin/env python3
"""Render PX4 px4_parameters.hpp template semantics without Jinja2."""

import argparse
from pathlib import Path
from xml.etree import ElementTree as ET


def read_parameters(xml_file: Path):
    root = ET.parse(xml_file).getroot()
    parameters = [
        parameter
        for group in root.findall("group")
        if "no_code_generation" not in group.attrib
        for parameter in group.findall("parameter")
    ]
    return sorted(parameters, key=lambda parameter: parameter.attrib["name"])


def storage_capacity(parameters) -> int:
    return 5 + sum(
        1 + len(parameter.attrib["name"].encode("utf-8")) + 1
        + (8 if parameter.attrib["type"] == "FLOAT" else 4)
        for parameter in parameters
    )


def render(parameters) -> str:
    lines = [
        "#pragma once", "", "#include <cstddef>", "#include <cstdint>", "",
        "// DO NOT EDIT: autogenerated from parameters.xml", "namespace px4 {",
        "enum class params : uint16_t {",
    ]
    lines.extend(f"    {parameter.attrib['name']}," for parameter in parameters)
    lines.extend([
        "};", "", f"static constexpr std::size_t param_info_count = {len(parameters)};",
        "static constexpr std::size_t parameter_storage_max_bytes = "
        f"{storage_capacity(parameters)};",
        "static constexpr uint8_t parameters_type[param_info_count] = {",
    ])
    lines.extend(f"    PARAM_TYPE_{parameter.attrib['type']}," for parameter in parameters)
    lines.extend(["};", "} // namespace px4", ""])
    return "\n".join(lines)


def generate(xml_file: Path, destination: Path | str = "."):
    target = Path(destination)
    target.mkdir(parents=True, exist_ok=True)
    parameters = read_parameters(xml_file)
    (target / "px4_parameters.hpp").write_text(render(parameters), encoding="utf-8")
    return parameters


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--xml", required=True, type=Path)
    parser.add_argument("--dest", default=Path("."), type=Path)
    args = parser.parse_args()
    generate(args.xml, args.dest)


if __name__ == "__main__":
    main()
