#ifndef DIMA_PLATFORM_API_PLATFORM_CONFIG_H
#define DIMA_PLATFORM_API_PLATFORM_CONFIG_H

#define DIMA_KERNEL_TICK_HZ 1000U
#define DIMA_CPU_CLOCK_HZ 480000000U
#define DIMA_MAX_SYSCALL_INTERRUPT_PRIORITY 5U
#define DIMA_LOWEST_INTERRUPT_PRIORITY 15U
#define DIMA_TASK_NAME_CAPACITY 16U

#endif /* DIMA_PLATFORM_API_PLATFORM_CONFIG_H */
